spring.application.name=Gohoubi_Hokkaido

spring.datasource.url=jdbc:postgresql://localhost:5432/gohoubi_hokkaido
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true